server:
  port: 8005

zuul:
#  忽略服务
  ignored-services: "*"
  routes:
    userservice:
      path: /userservice/**
      service-id: user
    taskcenter:
      path: /taskservice/**
      service-id: taskcenter
eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8000/eureka
  instance:
    preferIpAddress: true
spring:
  application:
    name: zuul
