server:
  port: 8000
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    service:
      name:
        task
    base-url: http://localhost:9411
    sender:
      type: web
eureka:
  server:
    # 注册信息缓存有效时长（s），默认180秒
    response-cache-auto-expiration-in-seconds: 60
    # 注册信息缓存更新间隔（s），默认30秒
    response-cache-update-interval-ms: 30
#  instance:
#    hostname: eureka
#    lease-renewal-interval-in-seconds: 30
#    lease-expiration-duration-in-seconds: 90
#
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8000